language: scala
scala:
   - 2.11.6
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean
  - sbt ++$TRAVIS_SCALA_VERSION coverage
  - sbt ++$TRAVIS_SCALA_VERSION test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coveralls