sudo: false
language: scala
scala:
   - 2.11.7
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test
after_success:
# The project is a multi-module project but with only one submodule valid for tests
# The aggregate only works if there are more than one submodule
#  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION ";project core ;coveralls"
  - sbt ++$TRAVIS_SCALA_VERSION ";project core ;codacyCoverage"
